version: '3.8'
services: 
  adminserver:
    env_file: 
      - .env
    environment: 
      - FDBU=${FDBU}
      - FDBP=${FDBP}
    container_name: api-server
    image: webdevops/php-nginx
    volumes:
      - ./www:/app
    ports:
      - 8080:80
      - 8081:443
